### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by robert36580** [jaegertracing/jaeger-ui#674] opened 2020-12-29 16:35 UTC
## Requirement - what kind of business use case are you trying to solve?

As stated in open-telemetry/opentelemetry-collector#2254 for performance reasons we want to be able to keep state for each consumer of a bounded queue so that we can reuse a certain struct.

## Problem - what in Jaeger blocks you from solving the requirement?

It's not currently possible to define a state for each consumer of a bounded queue: the public interface for the bounded queue only allows for providing a function and every consumer runs that function, so you can only keep a global state for all consumers.

https://github.com/jaegertracing/jaeger/blob/1b209472dc6a35f7de90c7a9048cb4e960cc2335/pkg/queue/bounded_queue.go#L61

## Proposal - what do you suggest to solve the problem or improve the existing situation?

A possible solution would work like this.

1. Define an interface like
```golang
type Consumer interface {
  Consume(item interface{})
}
```

2. Provide a new way to start a bounded queue with signature
```golang
func (q *BoundedQueue) StartConsumersWithFactory(num int, factory func() Consumer)
```
Reimplement consumer logic internally so that each consumer is built using the factory.

3. Rewrite `StartConsumers` using this factory
```golang
type statelessConsumer struct{
  consumefn func(item interface{}) 
}

func (c *statelessConsumer) Consume(item interface{}){
  c.consumefn(item)
}

func (q *BoundedQueue) StartConsumers(num int, consumer func(item interface{})) { 
  consumer := &statelessConsumer{consumer}
  q.StartConsumersWithFactory(num, func(){
    return consumer 
  })
}
```

## Any open questions to address

I think this would keep backwards-compatible behavior with minimal/no impact to performance but I am not a Go expert so that should be double-checked.

__Originally posted by @mx-psi in https://github.com/jaegertracing/jaeger/issues/2685__

**Comment by yurishkuro** [comment] 2020-12-29 17:14
Why is this in the UI repo?

**Comment by robert36580** [comment] 2021-01-04 14:42
@yurishkuro Careless mistake, my bad.

**Comment by yurishkuro** [comment] 2021-01-04 15:22
closing as duplicate of https://github.com/jaegertracing/jaeger/issues/2685

**Closed by yurishkuro** 2021-01-04 15:22 UTC
