### ISSUE TITLE
Possible issue with filtering by duration

### ISSUE THREAD

**Issue by jared-wallace** [jaegertracing/jaeger-ui#170] opened 2018-01-17 23:52 UTC
**Description**
I may not be understanding how the functionality works, but when I set the duration value to a minimum of 1ms, I get 64 traces, of which several are of duration 3-10 seconds. If I then set the minimum duration to 2s, I get no results. All other query parameters stay the same.

**Steps to reproduce the issue:**
1. Set minimum duration low, and see some results
2. Set minimum duration a bit higher, and see no results
3.

**Describe the results you received:**

<img width="1434" alt="first-censored" src="https://user-images.githubusercontent.com/6503051/35073206-89e8594c-fbad-11e7-9673-742bc7dc37e0.png">
<img width="673" alt="second-censored" src="https://user-images.githubusercontent.com/6503051/35073209-91fe9718-fbad-11e7-9872-82c856049247.png">

**Describe the results you expected:**
I would expect to see properly filtered traces - with a minimum of 2 seconds set, I expect all traces with durations exceeding 2 seconds to be shown.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (Browser, etc.):**
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
We have Jaeger ui, agent, collector and query all running in separate containers, reading off an elasticsearch backend.

**Comment by tiffon** [comment] 2018-01-19 16:26
@jared-wallace Thanks for reporting! Definitely looks like a bug. 

I'm not able to reproduce this with either our internal system or the all-in-one (which is running off an in-memory store).

@yurishkuro Is there an ES backed Jaeger available to trouble-shoot this?

**Comment by yurishkuro** [comment] 2018-01-19 20:24
> Is there an ES backed Jaeger available to trouble-shoot this?

yes, you can run Jaeger with ES backend.

**Comment by tiffon** [comment] 2018-01-21 01:01
@yurishkuro I know Jaeger can use ES as a store, I was wondering if we have something around that is using ES as the backend? Or, conversely, are there any docs on spinning one up? Something that expands on:

>pass the correct configuration values to the Jaeger collector and query service.
> — [deployment](http://jaeger.readthedocs.io/en/latest/deployment/#elasticsearch)

**Comment by black-adder** [comment] 2018-02-21 16:23
I don't think this is a bug. We'll have to do a better job of documenting cases like this though. Essentially, the duration search is done per span not per trace. So here, my guess is that you're searching for a service span whose duration is greater than 2s and there's no trace that meets that criteria.

We'd have to add an extra index in ES to add support for searching by trace duration (this isn't easily doable right now because to we don't know the duration of the entire trace until we've persisted all spans in a trace and we'd have to have a post processing job to handle this.)

@tiffon does the UI use the root span's duration as the duration of the trace? What happens if we have an async span that lasts way longer than the lifetime of the root span?

**Comment by tiffon** [comment] 2018-02-21 19:28
@black-adder Great clarification. Thank you. 

The UI calculates the trace duration. So, it should be resilient against async spans, etc.

**Comment by tiffon** [comment] 2018-03-12 00:50
@jared-wallace Can you confirm @black-adder's remarks?

**Comment by tiffon** [comment] 2018-03-23 19:59
Sounds like this is probably a non-issue. Closing until / unless @jared-wallace informs otherwise.

**Closed by tiffon** 2018-03-23 19:59 UTC
Labels: bug
