### ISSUE TITLE
UI show incorrect data for INT64 value

### ISSUE THREAD

**Issue by minhhungit** [jaegertracing/jaeger-ui#408] opened 2019-07-09 06:15 UTC
Sometime INT64 value in tag does not show correct on UI , and can not search by tag

for example:
long value: **212089821454139392**
but on UI, it shows **212089821454139400**, although I setup it as text

![image](https://user-images.githubusercontent.com/2279508/60863545-45deff80-a24b-11e9-89e9-cbab18609938.png)

**Comment by yurishkuro** [comment] 2019-07-09 15:45
I think  it's a duplicate of #396

**Closed by yurishkuro** 2019-07-09 15:45 UTC
Labels: duplicate
