### ISSUE TITLE
[Feature]: Speed up Critical path calculation

### ISSUE THREAD

**Issue by maxgaponov** [jaegertracing/jaeger-ui#1943] opened 2023-11-03 19:01 UTC
### Requirement

I would like to view big traces in Jaeger UI.

### Problem

Critical path calculation works slowly on large traces (especially if I press "Collapse all").

**Comment by yurishkuro** [comment] 2024-06-05 15:49
closing as duplicate of #2179, which has more information

**Closed by yurishkuro** 2024-06-05 15:49 UTC
Labels: enhancement
