### ISSUE TITLE
no way to retrieve all traces, regardless of operation name

### ISSUE THREAD

**Issue by trtg** [jaegertracing/jaeger-ui#52] opened 2017-08-10 23:10 UTC
The operation name has an "all" value in its dropdown, but when selecting that I receive only 3 results. If instead I pick some other arbitrary operation name that I know should be present in my traces, I have tons of results. Is 'all' supposed to return traces that contain any operation name?

**Comment by black-adder** [comment] 2017-08-11 14:25
Yes, all should return all traces for your service regardless of operation name. It looks and smells like a bug. Can you describe your current setup?

Are you running all-in-one (which version)?
Are you running cassandra or elastic search?

**Comment by tiffon** [comment] 2017-08-11 21:43
@trtg Can you also include samples of each request and response (with sensitive information redacted) for when you're searching with "all" vs with a specific endpoint name?

One way to get this info is to [copy it from the Chrome dev tools network tab](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#copy), either as a HAR file or as curl requests which can then be issued from a terminal.

Details: Open the developer tools, view the network tab, issue the requests (e.g. click search), right click the request in the table, in the copy sub-menu select copy as curl. Then, a curl can be issued.

**Comment by trtg** [comment] 2017-08-13 01:39
[curl_request_NO_operation_name.txt](https://github.com/uber/jaeger-ui/files/1220180/curl_request_NO_operation_name.txt)
[curl_request_with_operation_name.txt](https://github.com/uber/jaeger-ui/files/1220179/curl_request_with_operation_name.txt)

@tiffon here's the requests and responses you asked for. @black-adder We're running cassandra, two nodes, version 3.11

**Comment by black-adder** [comment] 2017-08-14 15:23
@trtg I wasn't able to reproduce on latest, could you provide the following details:
jaeger-query version
jaeger-collector version

**Comment by tiffon** [comment] 2017-08-17 11:55
@trtg Thanks for the curl commands. Can you include the response? The response should be relatively small if you limit the result set to just one trace.

**Comment by trtg** [comment] 2017-09-20 22:45
sorry for taking so long to follow up on this- if i use the stock docker image for jaeger-query using the docker-compose setup below, I see the following reproducible behavior: clicking "find traces" while 'all' is selected will always only show 2 results, no matter what the limit is set to. If instead of "all" I pick any other operation name, I can see all the results.

`jaeger_query:
    image: jaegertracing/jaeger-query
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: /go/bin/query-linux --query.static-files=/go/jaeger-ui/ --cassandra.keyspace jaeger_v1_datacenter1 --cassandra.servers cassandra.internal --cassandra.connections-per-host 2 --query.port 8380
    ports:
     - 8380:8380
`

**Comment by tiffon** [comment] 2018-02-06 02:53
I'm going to close this as it looks like it is not a UI issue and there is an issue created in Jaeger core to cover this.

We can reopen if the UI starts to play a role.

**Closed by tiffon** 2018-02-06 02:53 UTC
