### ISSUE TITLE
Rearrange the jaeger navigation to improve hierarchy

### ISSUE THREAD

**Issue by Danafrid** [jaegertracing/jaeger-ui#670] opened 2020-12-21 15:11 UTC
## Requirement - what kind of business use case are you trying to solve?

The current arrangement of items inside the main navigation of Jaeger causes confusion for the users - making them think the selected 'Search' tab is a button. The fix will improve ease of use.

## Problem - what in Jaeger blocks you from solving the requirement?

When searching by Trace ID when the Search tab is selected, users confuse the Search to be a button and try pressing it after filling in the Trace ID field. 

<img width="1792" alt="Screen Shot 2020-12-21 at 17 01 17" src="https://user-images.githubusercontent.com/75564311/102790732-94844900-43ae-11eb-862e-fc28f7b0b222.png">

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Rearrange the header by moving the search by TraceID to the right side (similar to Jira, for example) and move the tabs closer to the left. 

![Jaeger2](https://user-images.githubusercontent.com/75564311/102790965-f47aef80-43ae-11eb-836d-225e2390cf33.jpg)

**Comment by yurishkuro** [comment] 2020-12-21 18:02
Duplicate of #563

**Closed by yurishkuro** 2020-12-21 18:02 UTC
Labels: duplicate
